import { format } from 'date-fns'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export function exportBookPdf({ projectName, bookName, summary, entries }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageW = 595
  const pageH = 842

  // Background
  doc.setFillColor(253, 246, 231)
  doc.rect(0, 0, pageW, pageH, 'F')

  // Header band
  doc.setFillColor(214, 167, 94)
  doc.rect(0, 0, pageW, 72, 'F')

  // App name
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.text('ArthaLedger', 40, 38)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Where every rupee has meaning', 40, 56)

  // Date on right
  doc.setFontSize(9)
  doc.text(`Generated: ${format(new Date(), 'PPP p')}`, pageW - 40, 38, { align: 'right' })

  // Project & Book info
  doc.setTextColor(78, 58, 36)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text(bookName, 40, 104)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(120, 100, 70)
  doc.text(`Project: ${projectName}`, 40, 122)

  // Summary box
  doc.setFillColor(255, 250, 240)
  doc.setDrawColor(214, 167, 94)
  doc.setLineWidth(0.5)
  doc.roundedRect(40, 140, pageW - 80, 72, 8, 8, 'FD')

  const boxY = 168
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(78, 58, 36)

  // Total In
  doc.setTextColor(59, 159, 116)
  doc.text('Total In', 70, boxY - 10)
  doc.setFontSize(14)
  doc.text(`₹${summary.totalIn.toFixed(2)}`, 70, boxY + 8)

  // Total Out
  doc.setFontSize(11)
  doc.setTextColor(210, 111, 95)
  doc.text('Total Out', 240, boxY - 10)
  doc.setFontSize(14)
  doc.text(`₹${summary.totalOut.toFixed(2)}`, 240, boxY + 8)

  // Net Balance
  doc.setFontSize(11)
  const netColor = summary.net >= 0 ? [59, 159, 116] : [210, 111, 95]
  doc.setTextColor(...netColor)
  doc.text('Net Balance', 420, boxY - 10)
  doc.setFontSize(14)
  doc.text(`₹${summary.net.toFixed(2)}`, 420, boxY + 8)

  // Entries table
  const sortedEntries = [...entries].sort((a, b) => a.timestamp - b.timestamp)
  const rows = sortedEntries.map((entry) => [
    format(new Date(entry.timestamp), 'dd MMM yy'),
    entry.type === 'income' ? 'IN' : 'OUT',
    entry.description || '-',
    entry.category || '-',
    entry.mode || '-',
    entry.enteredBy || '-',
    `₹${Number(entry.amount).toFixed(2)}`,
    `₹${Number(entry.balanceAfter || 0).toFixed(2)}`,
  ])

  autoTable(doc, {
    startY: 232,
    head: [['Date', 'Type', 'Description', 'Category', 'Mode', 'By', 'Amount', 'Balance']],
    body: rows,
    styles: {
      fontSize: 8,
      textColor: [55, 40, 24],
      cellPadding: 5,
    },
    headStyles: {
      fillColor: [214, 167, 94],
      textColor: [43, 30, 17],
      fontStyle: 'bold',
      fontSize: 8,
    },
    alternateRowStyles: {
      fillColor: [255, 249, 236],
    },
    columnStyles: {
      1: {
        halign: 'center',
        fontStyle: 'bold',
      },
      6: { halign: 'right' },
      7: { halign: 'right', fontStyle: 'bold' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 1) {
        data.cell.styles.textColor = data.cell.raw === 'IN' ? [59, 159, 116] : [210, 111, 95]
      }
    },
  })

  // Footer
  const finalY = doc.internal.pageSize.height - 24
  doc.setFontSize(8)
  doc.setTextColor(160, 140, 110)
  doc.text('Generated by ArthaLedger — Where every rupee has meaning', 40, finalY)
  doc.text(`${entries.length} entries`, pageW - 40, finalY, { align: 'right' })

  doc.save(`${bookName.replace(/\s+/g, '_').toLowerCase()}_santham_ledger.pdf`)
}
